name       : pdal
version    : 2.3.0
release    : 2
source     :
    - https://github.com/PDAL/PDAL/releases/download/2.3.0/PDAL-2.3.0-src.tar.bz2 : 63d8d4fee491675f0fa3dca58c26d57fb2afcaa37c24b10f595b3fbff174996e
license    : BSD-2-Clause
component  : programming.library
summary    : Library for translating and manipulating point cloud data
description: |
    PDAL (Point Data Abstraction Library) is a C/C++ open source library and applications for translating and processing point cloud data.
clang      : yes
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(geos)
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(hdf5)
    - pkgconfig(jsoncpp)
    - pkgconfig(laszip)
    - pkgconfig(libcurl)
    - pkgconfig(libpq)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzstd)
    - pkgconfig(openscenegraph)
    - pkgconfig(pcl_io)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - pkgconfig(xerces-c)
    - cpd-devel
    - fgt-devel
    - laz-perf-devel
    - libgeotiff-devel
    - numpy
setup      : |
    %patch -p1 < $pkgfiles/use-supported-OpenSceneGraph-API.patch
    %patch -p1 < $pkgfiles/missing-includes.patch
    %cmake_ninja \
        -DPDAL_LIB_INSTALL_DIR=lib64 \
        -DBUILD_PLUGIN_PYTHON=ON \
        -DBUILD_PLUGIN_CPD=ON \
        -DBUILD_PLUGIN_E57=ON \
        -DBUILD_PLUGIN_HDF=ON \
        -DBUILD_PLUGIN_I3S=ON \
        -DBUILD_PLUGIN_ICEBRIDGE=ON \
        -DBUILD_PLUGIN_NITF=OFF \
        -DBUILD_PLUGIN_OPENSCENEGRAPH=ON \
        -DBUILD_PLUGIN_PGPOINTCLOUD=ON \
        -DBUILD_PLUGIN_SQLITE=ON \
        -DBUILD_PGPOINTCLOUD_TESTS=OFF \
        -DWITH_LAZPERF=ON \
        -DWITH_LASZIP=ON \
        -DWITH_COMPLETION=ON \
        -DWITH_TESTS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
